[package]
name = "jwmerrill/lox-repl"
version = "0.1.1"
description = "A REPL for the Lox langauge described in Bob Nystrom's \"Crafting Interpreters\""
license = "MIT"
repository = "https://github.com/jwmerrill/zig-lox/"

[[module]]
name = "lox-repl"
source = "build/lox-repl.wasm"
abi = "wasi"

[module.interfaces]
wasi = "0.0.0-unstable"

[[command]]
name = "lox-repl"
module = "lox-repl"
